---
    
iol-01:
    hostname: "192.168.100.7"
    groups:
        - cisco_group
        - usa_group

iol-02:
    hostname: "192.168.100.6"
    groups:
        - cisco_group
        - euro_group
        
csr-01:
    hostname: "192.168.100.5"
    groups:
        - cisco_group