---

R1:
    hostname: "192.168.100.7"
    groups:
        - cisco_group
        - usa_group

R2:
    hostname: "192.168.100.6"
    groups:
        - cisco_group
        - euro_group
        
R3:
    hostname: "192.168.100.5"
    groups:
        - cisco_group